stable

diff --git a/mgmt/validation/helm/loki-base/rules/threat-intel/loki-scripts.yaml b/mgmt/validation/helm/loki-base/rules/threat-intel/loki-scripts.yaml
--- a/mgmt/validation/helm/loki-base/rules/threat-intel/loki-scripts.yaml
+++ b/mgmt/validation/helm/loki-base/rules/threat-intel/loki-scripts.yaml
@@ -18,7 +18,8 @@ data:
           description: "Malicious IP Detected"
           tenant_id: achref
           topic: acculens
-          tool: {{ .Labels.job }}
+          tool: |
+            {{ .Labels.job }}
 
   threat-intel.sh: |
     #!/bin/bash
@@ -26,12 +27,24 @@ data:
     export BLOCK_LIST=$(curl https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/5.txt | grep -v "#" | awk '{print $1}' | sed 's/\./\\\\./g' | paste -sd'|' -)
     TMP_FILE=$(mktemp)
     envsubst < threat-intel.rule > $TMP_FILE
-    response=$(curl -H"$TENANT_USERNAME" -X POST -H "Content-Type: application/yaml" --data-binary "@$TMP_FILE" "$LOKI_GW_SVC/loki/api/v1/rules/threat-intel")
-    if [[ "$response" == *'"status":"success"'* ]]; then
-      echo "Successfully applied $TMP_FILE"
-    else
-      echo $response
-      echo "ERROR: Loki did not return success for $TMP_FILE"
-      echo "Response was: $TMP_FILE"
-      exit 1
-    fi
+    for ns in $(kubectl get namespace -o name -l env -l tenant | cut -d"/" -f2)
+    do
+      env=$(kubectl get ns $ns -o jsonpath='{.metadata.labels.env}')
+      user=$(echo $ns | sed "s/^tenant-//g")
+      tenant="$env-$user"
+      echo "Processing Tenant= $tenant"
+      response=$(curl -H"X-Scope-OrgID: $tenant" -X POST -H "Content-Type: application/yaml" --data-binary "@$TMP_FILE" "$LOKI_GW_SVC/loki/api/v1/rules/threat-intel")
+      if [[ "$response" == *'"status":"success"'* ]]; then
+        echo "Successfully applied $TMP_FILE"
+      else
+        echo $response
+        echo "ERROR: Loki did not return success for $TMP_FILE"
+        echo "Response was: $TMP_FILE"
+        exit 1
+      fi
+    done
+    envsubst <  /retreiver-cm-template/loki-rules.yaml > $TMP_FILE
+    CMD='.data."foobar" = load_str("'"$TMP_FILE"'")'
+    echo "data: " | yq "$CMD" > /tmp/patch.yaml
+    kubectl patch cm retriver-cm -n retreiver --patch-file /tmp/patch.yaml
+    kubectl rollout restart deployment/retreiver-retriver -n retreiver
